server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}


info:
  app:
    name: API Gateway
    description: Gateway para enrutar servicios vía Eureka
    version: 1.0.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG