server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: citas-service
          uri: lb://citas-service
          predicates:
            - Path=/digital/hospital/appointments/**
          filters:
            - RewritePath=/digital/hospital/appointments/(?<segment>.*), /appointments/${segment}

        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/digital/hospital/doctors/**
          filters:
            - RewritePath=/digital/hospital/doctors/(?<segment>.*), /doctors/${segment}

        - id: especialidad-service
          uri: lb://especialidad-service
          predicates:
            - Path=/digital/hospital/specialties/**
          filters:
            - RewritePath=/digital/hospital/specialties/(?<segment>.*), /specialties/${segment}

        - id: paciente-service
          uri: lb://paciente-service
          predicates:
            - Path=/digital/hospital/patients/**
          filters:
            - RewritePath=/digital/hospital/patients/(?<segment>.*), /patients/${segment}
      discovery:
        enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin,*
        - AddResponseHeader=Access-Control-Allow-Methods,"GET,POST,PUT,DELETE,PATCH,OPTIONS"
        - AddResponseHeader=Access-Control-Allow-Headers,*
        - AddResponseHeader=Access-Control-Allow-Credentials,true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - ${ALLOWED_ORIGINS:*}
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://localhost:8080"
              - "https://cliente.com"
              - "https://*.vercel.app"
              - "https://*.netlify.app"
            allowedHeaders: 
              - "*"
              - "Content-Type"
              - "Authorization"
              - "X-Requested-With"
              - "Accept"
              - "Origin"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowCredentials: true
            maxAge: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  metrics:
    enable:
      system.cpu: false
      process.cpu: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka} 
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

info:
  app:
    name: API Gateway
    description: Gateway para enrutar servicios vía Eureka
    version: 1.0.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.nettx.http.client: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG