server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: citas-service
          uri: ${CITAS_SERVICE_URL:http://citas-service-dev.up.railway.app}
          predicates:
            - Path=/digital/hospital/appointments/**
          filters:
            - RewritePath=/digital/hospital/appointments/(?<segment>.*), /appointments/${segment}

        - id: doctor-service
          uri: ${DOCTOR_SERVICE_URL:http://doctor-service-dev.up.railway.app}
          predicates:
            - Path=/digital/hospital/doctors/**
          filters:
            - RewritePath=/digital/hospital/doctors/(?<segment>.*), /doctors/${segment}

        - id: especialidad-service
          uri: ${ESPECIALIDAD_SERVICE_URL:http://especialidad-service-dev.up.railway.app}
          predicates:
            - Path=/digital/hospital/specialties/**
          filters:
            - RewritePath=/digital/hospital/specialties/(?<segment>.*), /specialties/${segment}

        - id: paciente-service
          uri: ${PACIENTE_SERVICE_URL:http://paciente-service-dev.up.railway.app}
          predicates:
            - Path=/digital/hospital/patients/**
          filters:
            - RewritePath=/digital/hospital/patients/(?<segment>.*), /patients/${segment}
      discovery:
        enabled: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:*}
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH

# Deshabilitar Eureka en producción
eureka:
  client:
    enabled: false
  instance:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics
  metrics:
    enable:
      system.cpu: false
      process.cpu: false
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
    metrics:
      enabled: false
  info:
    env:
      enabled: true

info:
  app:
    name: API Gateway
    description: Gateway para enrutar servicios en producción
    version: 1.0.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

ENABLE_CORS: true
CORS_ALLOWED_ORIGINS: https://cliente.com,http://localhost:5173
